remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Hanie's Portfolio]
description: [Below are the projects that I have done while studying for my Master's degree of Business Analytics at Macquarie University]


